// SUMA
var a = 10+4;
console.log(a)

//RESTA
var b= 20-18;
console.log(b)

//MULTIPLICACIÓN
var c= 4.5*5;
console.log(c)

//DIVISION
var d= 40/10;
console.log(d)

//RESIDUO
var RESIDUO = 20%3;
console.log(RESIDUO)

//POTENCIA
var potencia = 5**3;
console.log(potencia)

//OPERADORES DE COMPARACIÓN

//IGUALDAD
var prueba= 4;
var prueba2= 8;
console.log(prueba===prueba2);

//DISTINTOS
var numero= 6;
var numero1= 2;
console.log(numero!==numero1);

//MAYOR
var ayuda= 15
var ayuda1= 20
console.log(ayuda>ayuda1);

//MAYOR O IGUAL
console.log(15>=15);

//MENOR O IGUAL
console.log(19<=19)


//OPERADORES LÓGICOS

//  0
console.log(4>5 ||  8>9);

//  Y
console.log(6<10 && 12<15);

//NEGACIÓN
console.log(!false);

//COMPARACIÓN DE TEXTOS (STRING)
var mensaje = "hola como estas";
var mensaje1 = "hola como estas";
console.log(mensaje!==mensaje1);